# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- 1-start

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'lab20'
    organization: 'learningdevops0717'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'lab20.prateek'
    cliProjectName: 'lab20'
    cliSources: '.'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: SonarCloudAnalyze@1